In [1]:
import schwordcloud
from pathlib import Path
import pandas as pd

In [2]:
cloud_annotation_file = Path(r'D:\Users\maxwelfreitas\ANATEL\InovaFiscaliza - DataHub - GET\SCH\Annotation.xlsx')
local_annotation_folder = r'E:\datasets\sch\annotation'
null = r'C:\Users\maxwelfreitas\AppData\Local\schwordcloud\datasets\annotation\NullAnnotation.xlsx'
df_annotation = schwordcloud.fetch_annotation(cloud_annotation_file,null,local_annotation_folder)
df_annotation.head()

,ID,DataHora,Computador,Usuário,Homologação,Atributo,Valor,Situação,Scarab Post Order
0,001f8c9b-c83f-488c-8bd4-fe92909a51ec,08/08/2024 11:31:59,ES6927559DTL,maxwelfreitas,03685-11-05967,WordCloud,"{""metaData"": {""Version"": 1, ""Source"": ""BING"", ...",0,0
1,00225394-f4a7-4e96-8c33-d84dafefa1ac,06/10/2024 11:30:28,ES6927559DTL,maxwelfreitas,15152-21-13346,WordCloud,"{""metaData"": {""Version"": 1, ""Source"": ""GOOGLE""...",0,1
2,002562da-097d-4f53-ae34-6ae6f92e9b48,24/09/2024 11:33:24,ES6927559DTL,maxwelfreitas,00183-04-02137,WordCloud,"{""metaData"": {""Version"": 1, ""Source"": ""BING"", ...",0,2
3,003c2c5c-7823-41b8-978b-85c3f859d7cf,16/11/2024 15:00:42,WIFIPRTITSIN09,admin.fiprtiwi009.s1,16422-21-06146,WordCloud,"{""metaData"": {""Version"": 1, ""Source"": ""BING"", ...",0,3
4,004631d8-85b5-4dad-b6de-5a7c8bd29659,30/10/2024 05:00:22,WIFIPRTITSIN09,admin.fiprtiwi009.s1,07709-23-12298,WordCloud,"{""metaData"": {""Version"": 1, ""Source"": ""GOOGLE""...",0,4

In [3]:
local_sch_folder = r'C:\Users\maxwelfreitas\AppData\Local\schwordcloud\datasets\sch'
df_sch = schwordcloud.fetch_sch_database(local_sch_folder)
columns_to_keep = ["Número de Homologação", "Data da Homologação", "Categoria do Produto"]
df_sch = df_sch[columns_to_keep]
df_sch = df_sch.drop_duplicates(subset="Número de Homologação")
df_sch

       Número de Homologação Data da Homologação  Categoria do Produto
0               041141303428          2025-04-03                     3
2               044571407864          2015-01-23                     3
4               037411102482          2017-09-21                     3
5               037401102482          2017-10-01                     3
6               001510500554          2005-02-21                     3
...                      ...                 ...                   ...
160008          199842315957          2023-10-19                     2
160009          199932302492          2023-10-17                     2
160011          199952315053          2023-10-19                     2
160012          199972312523          2023-10-17                     2
160013          200422314594          2023-11-21                     2

[75937 rows x 3 columns]

In [4]:
cloud_annotation_file = Path(r'D:\Users\maxwelfreitas\ANATEL\InovaFiscaliza - DataHub - GET\SCH\Annotation.xlsx')
local_annotation_folder = r'E:\datasets\sch\annotation'
null = r'C:\Users\maxwelfreitas\AppData\Local\schwordcloud\datasets\annotation\NullAnnotation.xlsx'
df_annotation = schwordcloud.fetch_annotation(cloud_annotation_file,null,local_annotation_folder)

columns_to_merge = ["Homologação", "DataHora", "ID"]
df_annotation = df_annotation[columns_to_merge]
df_annotation.columns = ["Número de Homologação", "Data da Busca", "ID"]
df_annotation["Número de Homologação"] = df_annotation["Número de Homologação"].apply(lambda numero_homologacao: numero_homologacao.replace("-", ""))

df_to_search = df_sch.merge(df_annotation, how="left")
df_to_search = df_to_search[df_to_search["ID"].isna()]
df_to_search["Dias da Homologação"] = df_to_search["Data da Homologação"].apply(lambda data_homologacao: (pd.Timestamp.now() - data_homologacao).days)
df_to_search

,Número de Homologação,Data da Homologação,Categoria do Produto,Data da Busca,ID,Dias da Homologação
0,041141303428,2025-04-03,3,NaN,NaN,19
1,044571407864,2015-01-23,3,NaN,NaN,3742
2,037411102482,2017-09-21,3,NaN,NaN,2770
3,037401102482,2017-10-01,3,NaN,NaN,2760
4,001510500554,2005-02-21,3,NaN,NaN,7365
...,...,...,...,...,...,...
76926,010232513127,2025-03-08,2,NaN,NaN,45
76927,011272504380,2025-03-07,3,NaN,NaN,46
76928,011312504380,2025-03-07,3,NaN,NaN,46
76930,062191910291,2023-09-25,3,NaN,NaN,575
76931,014092515969,2025-03-26,3,NaN,NaN,27